### PR TITLE
Add support for djangoCMS 4.x

### LINKED ISSUE #221: in dijango-cms 4.1 and fronted
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "dev/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "dev/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "dev/lib/python3.11/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "dev/lib/python3.11/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "dev/lib/python3.11/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "dev/lib/python3.11/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "dev/lib/python3.11/site-packages/cms/plugin_pool.py", line 42, in discover_plugins
    autodiscover_modules('cms_plugins')
  File "dev/lib/python3.11/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "dev/lib/python3.11/site-packages/djangocms_link/cms_plugins.py", line 7, in <module>
    from .forms import LinkForm
  File "dev/lib/python3.11/site-packages/djangocms_link/forms.py", line 10, in <module>
    class LinkForm(ModelForm):
  File "dev/lib/python3.11/site-packages/djangocms_link/forms.py", line 11, in LinkForm
    internal_link = PageSearchField(
                    ^^^^^^^^^^^^^^^^
  File "dev/lib/python3.11/site-packages/djangocms_link/fields_select2.py", line 45, in __init__
    kwargs['queryset'] = self.widget.get_queryset()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dev/lib/python3.11/site-packages/djangocms_link/fields_select2.py", line 32, in get_queryset
    return Page.objects.drafts()
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PageManager' object has no attribute 'drafts'

### PR DESCRIPTION
**Pull request by filipweidemann**
## Description

This PR adds support for the new djangoCMS 4.x.
It closes #221 and uses the outlined approach discussed there.

I also refactored the test setup and added the Mixin/Fixture of djangocms-text-ckeditor4 to support both djangoCMS 3 & 4.

All tests are green locally, I'd be happy to get this merged if everything is looking good to you @fsbraun :)

## Related resources

* https://github.com/django-cms/djangocms-text-ckeditor/blob/master/tests/fixtures.py

## Checklist

* [ x ] I have opened this pull request against ``master``
* [ x ] I have added or modified the tests when changing logic
* [ x ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ x ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by fsbraun** [comment]
This PR supersedes #201

**Comment by filipweidemann** [comment]
Oh man I knew it, I'll quickly sort the test files as well...

**Comment by filipweidemann** [comment]
@fsbraun I `isort`ed the tests/ directory as well, sorry for the miss there.

**Review by fsbraun — APPROVED** [review]
@filipweidemann Thank you so much for this nice PR!

**Comment by filipweidemann** [comment]
Ofc, thanks for the merge as well :)

**Comment by fsbraun** [comment]
@filipweidemann Released as version 4.0 🎉

**Comment by filipweidemann** [comment]
@fsbraun lovely, thank you so much 🙏

**Pull request merged**
